title: {"Hey I'm": Tarun Mishra}
description: >
  A results-driven Data Scientist who extracts insights faster than AI evolves—
  constantly learning, adapting, and staying ahead in the ever-accelerating world of tech.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_repo: jekyll # the GitHub repo name for your project
github_username: jekyll

# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
social_link: twitter
social_username: jekyllrb

# Set theme color here
# Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow.
theme_color: black

# Build settings
markdown: kramdown
