remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
header_pages:
  - README.md
author:
  name: Tarun Pramod Mishra
  email: tarunpmishra2001@gmail.com
title: tarun.ai
logo: Portrait_TarunPMishra_Circle..png
description: A results-oriented Data Science professional adept at extracting actionable insights from complex datasets.
#show_downloads: true
show_downloads: false
is_project_page: false
