title: Tarun Mishra
logo: Portrait_TarunPMishra_Circle..png
description: A results-oriented Data Science professional adept at extracting actionable insights from complex datasets.
#show_downloads: true
theme: jekyll-theme-minimal
