title: Tarun Pramod Mishra
logo: Portrait_TarunPMishra_Circle..png
description: A results-driven Data Science professional with a solid foundation in Python, SQL, and Big Data technologies. Skilled in extracting actionable insights from complex datasets, optimizing business processes, and driving impactful decisions. Adept at leveraging analytical methodologies to solve real-world problems and deliver value to stakeholders. Passionate about continuous learning and staying abreast of emerging trends in data science and technology.
show_downloads: true
theme: jekyll-theme-minimal
