title: Tarun Mishra
logo: Portrait_TarunPMishra_Circle..png
description: Results-driven Data Science professional ,skilled in extracting actionable insights from complex datasets.
show_downloads: true
theme: jekyll-theme-minimal
